name: Continuous Integration

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: '3.10'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r backend/requirements.txt
    
    - name: Run linters
      run: |
        pip install flake8 black
        flake8 backend
        black --check backend
    
    - name: Run tests
      run: |
        pip install pytest
        cd backend
        pytest test_main.py

  build-docker:
    needs: test
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Build Docker image
      run: docker build -t library-management-system ./backend
    
    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
      
    - name: Push to Docker Hub
      run: |
        docker tag library-management-system ${{ secrets.DOCKERHUB_USERNAME }}/library-management-system:latest
        docker push ${{ secrets.DOCKERHUB_USERNAME }}/library-management-system:latest
